import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { Header } from "./movies/_components/Header";
import { MovieFooter } from "./movies/_components/Footer";

export const metadata: Metadata = {
  title: "Movie App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <NextThemesProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* defaultTheme="system"- anhni theme-g systemiin daguu songono
           enableSystem-	Системийн theme-г зөвшөөрнө
           disableTransitionOnChange	Theme өөрчлөгдөх үед анимэйшн хийхгүй
          //  */}
          <Header />

          {children}
          <MovieFooter />
        </NextThemesProvider>
      </body>
    </html>
  );
}
